apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  IDP_LABEL: "okta"
  IDP_CLIENT_ID: {{ .Values.oidc_client_id }} 
  IDP_ISSUER: {{ .Values.oidc_issuer_url }}
  IDP_AUDIENCE: "api://helloworld"
  IDP_LOGIN_CALLBACK: "https://helloworld.{{ .Values.domainName }}/auth/login/token"
  IDP_ISSUER_LOGOUT_PATH : "/v1/logout"
  S3_BUCKET: {{ .Values.s3_bucket }} 
  AWS_REGION_OVERRIDE: {{ .Values.awsRegionOverride }}