# Default values for configserver-chart.
# This is a YAML-formatted file.
#
# This file provides project specific variables and is joined with another value file
# in MasterDeployments or MinikubeDeployment repos.
#
# When helm is launched it will be done so like this:
#
#  helm template -f <valuesfile> <chartlocation>  > outputfile
#
# and the output will be redirected to a yaml file which will then be manually kubectl applied

# local variables for this deployment can go here

ingress:
  ingressClassName: nginx-internal
  apiVersion: networking.k8s.io/v1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-staging

dockerPreamable: 626007623524.dkr.ecr.us-east-2.amazonaws.com/eti-sre
domainPrefix: helloworld-go
servicePort: "5000"
metricsPort: "5001"
dbname: helloworlddev

oidc_client_id: SET_IN_DEPLOYMENT_REPO
oidc_issuer_url: SET_IN_DEPLOYMENT_REPO

grafana:
  folderName: eti-sre
  ventureName: eti-sre
  appInstance: one-eye-grafana-operator
  appName: grafana-operator

# Environment-specific values
namespace: SET_IN_DEPLOYMENT_REPO       # Overridden in deployment repo for env-specific namespace
tagversion: SET_IN_DEPLOYMENT_REPO      # Defer to deployment repo to capture appropriate version for target environment
dimage: SET_IN_DEPLOYMENT_REPO          # Defer to deployment repo to capture appropriate image name for dev/staging/prod
domainName: SET_IN_DEPLOYMENT_REPO      # Defer to deployment repo to capture appropriate domain name for dev/staging/prod
replicas: 1                             # Default replica count; override in deployment repo for env-specific replica count
deploymentEnv: SET_IN_SRE_CLUSTER_CONFIG_REPO # Defer to sre_cluster_config repo; Value of this param should not impact application
s3_bucket: SET_IN_DEPLOYMENT_REPO       # Defer to deployment repo to capture appropriate s3 bucket name for dev/staging/prod
awsRegionOverride: SET_IN_DEPLOYMENT_REPO   # Defer to deployment repo to capture appropriate aws_region for dev/staging/prod
serviceAccount:
  # Specifies whether a service account should be created
  create: false                         # Override in deployment repo to capture appropriate IAM role arn annotation
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
externalSecrets:                        # Placeholder/example for specifying secrets retrieval
  secretStoreName: SET_IN_DEPLOYMENT_REPO
  secretStoreKind: SET_IN_DEPLOYMENT_REPO
  data:
  - secretKey: EXAMPLE_PLACEHOLDER
    remoteRef:
      key: EXAMPLE_PLACEHOLDER
      version: "1"
      property: EXAMPLE_PLACEHOLDER
